{{- if .Values.baseURL }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: json-dataviz-ingress
spec:
  rules:
  - host: {{ .Release.Name }}-api.{{ .Values.baseURL }}
    http:
      paths:
      - backend:
          serviceName: json-dataviz
          servicePort: 5000
        path: /
        pathType: ImplementationSpecific
  - host: {{ .Release.Name }}.{{ .Values.baseURL }}
    http:
      paths:
      - backend:
          serviceName: json-dataviz
          servicePort: 8080
        path: /
        pathType: ImplementationSpecific
{{- end }}