apiVersion: v1
kind: Service
metadata:
  name: json-dataviz
  labels:
    app: json-dataviz
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http-api
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-front
  selector:
    app: json-dataviz